################################################################################
# Alvaro Araya 2020                                                            #
################################################################################

version: '3.7'

services:
  db:
    image: 'mariadb'
    restart: always
    container_name: 'mariadb-pandemics'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ROOT_PASSWORD: Acces0
      MYSQL_DATABASE: pandemicsdb
      MYSQL_USER: pandemics_root
      MYSQL_PASSWORD: Acces0
    ports:
      - "3306:3306"
    volumes:
      - pandemics-data:/var/lib/mysql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pandemics-data: